import Head from "next/head";
import { Box, Container } from "@mui/material";
import Grid from "@mui/material/Unstable_Grid2";

export default function Home() {
  return (
    <>
      <Head>
        <title>Something</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
          <Box component={"form"}
               autoComplete="off" >



          </Box>
      </Container>
    </>
  );
}
